# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 863418ca22c05559a5cc42d71075a4cc89b15640878348a17288c467fd89838d2b6d3bcc1934fde9404d187948fe176af81c5f4ccf713ac3962aa82f9e11b559

test:
  secret_key_base: 6ee4a9e64fcf16146771cbab296236a53418847336ac814705327df3b78253a8535ab9ed6c0367080a453a60163f59428d3ae0f4e18a0db9b188e5d16a92d329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
